/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cine.Views;

import com.mycompany.cine.Controller.ConectorDB;
import com.mycompany.cine.Controller.PeliculaController;
import com.mycompany.cine.Model.PeliculaDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mlarr
 */
public class EditorPelicula extends javax.swing.JPanel {

    /**
     * Creates new form EditorPelicula
     */
    public EditorPelicula(ConectorDB conn) {
        this.conector = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldtAnno = new javax.swing.JTextField();
        jLabelDuracion = new javax.swing.JLabel();
        jLabelAnno = new javax.swing.JLabel();
        jTextFieldtDuracion = new javax.swing.JTextField();
        jLabelDirector = new javax.swing.JLabel();
        jTextFieldtDirector = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldtITitulo = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldtGenero = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jLabelPelicula = new javax.swing.JLabel();
        jButtonAñadir = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldtAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtAnnoActionPerformed(evt);
            }
        });
        jTextFieldtAnno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtAnnoKeyTyped(evt);
            }
        });

        jLabelDuracion.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelDuracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDuracion.setText("Duración:");
        jLabelDuracion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelAnno.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelAnno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAnno.setText("Año:");
        jLabelAnno.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextFieldtDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtDuracionKeyTyped(evt);
            }
        });

        jLabelDirector.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDirector.setText("Director:");

        jTextFieldtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtDirectorActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitulo.setText("Titulo:");

        jLabelID.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelID.setText("Id:");

        jTextFieldID.setEditable(false);

        jTextFieldtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtGeneroActionPerformed(evt);
            }
        });

        jLabelGenero.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGenero.setText("Género:");
        jLabelGenero.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelPelicula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabelPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPelicula.setText("Nueva Pelicula");

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDirector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldtITitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabelDuracion)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtITitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonLimpiar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 663, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtDirectorActionPerformed

    private void jTextFieldtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtGeneroActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed

        //Añadir
        if (accion == 1) {
            if (this.jTextFieldtITitulo.getText().isEmpty() || this.jTextFieldtDirector.getText().isEmpty() || this.jTextFieldtAnno.getText().isEmpty() || this.jTextFieldtDuracion.getText().isEmpty() || this.jTextFieldtGenero.getText().isEmpty()) {
                System.out.println("No todos los datos están ingresados");
                    JOptionPane.showMessageDialog(null, "Debe ingresar todos los datos", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                if (Integer.valueOf(this.jTextFieldtAnno.getText()) < 1900) {
                    JOptionPane.showMessageDialog(null, "El año no puede ser menor a 1900", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else if (Integer.valueOf(this.jTextFieldtAnno.getText()) > 9999) {
                    JOptionPane.showMessageDialog(null, "El año no puede tener más de 4 digitos", "ERROR", JOptionPane.WARNING_MESSAGE);

                } else if (Integer.valueOf(this.jTextFieldtDuracion.getText()) > 999) {
                    JOptionPane.showMessageDialog(null, "Duración no puede exceder los 3 dígitos", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else if (Integer.valueOf(this.jTextFieldtDuracion.getText()) <= 0) {
                    JOptionPane.showMessageDialog(null, "Duración debe ser min 1 min", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else {
                    System.out.println("Datos ingresador");

                    PeliculaDAO peliculaNueva = new PeliculaDAO();

                    peliculaNueva.setTitulo(this.jTextFieldtITitulo.getText());
                    peliculaNueva.setDirector(this.jTextFieldtDirector.getText());
                    peliculaNueva.setAnno(Integer.valueOf(jTextFieldtAnno.getText()));
                    peliculaNueva.setDuracion(Integer.valueOf(this.jTextFieldtDuracion.getText()));
                    peliculaNueva.setGenero(this.jTextFieldtGenero.getText());

                    PeliculaController controller = new PeliculaController();
                    try {
                        controller.agregarPeliculaController(peliculaNueva, this.conector.getConn());
                        JOptionPane.showMessageDialog(null, "Se ha agregado la película correctamente", "Ingreso", JOptionPane.INFORMATION_MESSAGE);
                        this.jTextFieldtITitulo.setText("");
                        this.jTextFieldtDirector.setText("");
                        this.jTextFieldtAnno.setText("");
                        this.jTextFieldtDuracion.setText("");
                        this.jTextFieldtGenero.setText("");
                        Principal.mostrarPanel(new ListaPeliculas(this.conector));

                    } catch (SQLException ex) {
                        Logger.getLogger(EditorPelicula.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            }
        } else if (accion == 2) {
            //Modificar
            
            if (this.jTextFieldtITitulo.getText().isEmpty() || this.jTextFieldtDirector.getText().isEmpty() || this.jTextFieldtAnno.getText().isEmpty() || this.jTextFieldtDuracion.getText().isEmpty() || this.jTextFieldtGenero.getText().isEmpty()) {
                System.out.println("No todos los datos están ingresados");

                JOptionPane.showMessageDialog(null, "Debe ingresar todos los datos", "ERROR", JOptionPane.WARNING_MESSAGE);


            } else {
                 if (Integer.valueOf(this.jTextFieldtAnno.getText()) < 1900) {
                    JOptionPane.showMessageDialog(null, "El año no puede ser menor a 1900", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else if (Integer.valueOf(this.jTextFieldtAnno.getText()) > 9999) {
                    JOptionPane.showMessageDialog(null, "El año no puede tener más de 4 digitos", "ERROR", JOptionPane.WARNING_MESSAGE);

                } else if (Integer.valueOf(this.jTextFieldtDuracion.getText()) > 999) {
                    JOptionPane.showMessageDialog(null, "Duración no puede exceder los 3 dígitos", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else if (Integer.valueOf(this.jTextFieldtDuracion.getText()) <= 0) {
                    JOptionPane.showMessageDialog(null, "Duración debe ser min 1 min", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{
                    PeliculaDAO peliculaNuevo = new PeliculaDAO();
                    peliculaNuevo.setId(id);
                    peliculaNuevo.setTitulo(jTextFieldtITitulo.getText());
                    peliculaNuevo.setDirector(jTextFieldtDirector.getText());
                    peliculaNuevo.setAnno(Integer.valueOf(jTextFieldtAnno.getText()));
                    peliculaNuevo.setDuracion(Integer.valueOf(jTextFieldtDuracion.getText()));
                    peliculaNuevo.setGenero(jTextFieldtGenero.getText());

                    PeliculaController controlador = new PeliculaController();
                    try {
                        controlador.modificarVehiculoIdController(peliculaNuevo, this.conector.getConn());
                        JOptionPane.showMessageDialog(null, "Se ha modificado la película " + peliculaNuevo.getTitulo(), "Exito", JOptionPane.INFORMATION_MESSAGE);
                        this.jTextFieldtITitulo.setText("");
                        this.jTextFieldtDirector.setText("");
                        this.jTextFieldtAnno.setText("");
                        this.jTextFieldtDuracion.setText("");
                        this.jTextFieldtGenero.setText("");
                        Principal.mostrarPanel(new ListaPeliculas(this.conector));
                    } catch (SQLException ex) {
                        Logger.getLogger(EditorPelicula.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }


    }//GEN-LAST:event_jButtonAñadirActionPerformed
    private void jTextFieldtAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtAnnoActionPerformed
  
    }//GEN-LAST:event_jTextFieldtAnnoActionPerformed

    private void jTextFieldtAnnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtAnnoKeyTyped
        System.out.println("Typed");
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldtAnnoKeyTyped

    private void jTextFieldtDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtDuracionKeyTyped
        System.out.println("Typed");
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldtDuracionKeyTyped

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        this.jTextFieldtITitulo.setText("");
        this.jTextFieldtDirector.setText("");
        this.jTextFieldtAnno.setText("");
        this.jTextFieldtDuracion.setText("");
        this.jTextFieldtGenero.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    
    public void setTitulo(String texto, String texto2, int accion, int id){
        this.jLabelPelicula.setText(texto);
        this.jButtonAñadir.setText(texto2);
        this.accion = accion;
        this.id = id;
        if (id != 0 && id != -1){
            modificarPelicula();
        }    
    }
    
    private void modificarPelicula(){
        PeliculaDAO pelicula = new PeliculaDAO();
        pelicula.setId(id);
        
        PeliculaController controlador = new PeliculaController();
        try {
            boolean flag = controlador.buscarPeliculaController(pelicula, this.conector.getConn());
            
            if (flag == true) {
                jTextFieldID.setText(Integer.toString(pelicula.getId()));
                jTextFieldtITitulo.setText(pelicula.getTitulo());
                jTextFieldtDirector.setText(pelicula.getDirector());
                jTextFieldtAnno.setText(Integer.toString(pelicula.getAnno()));
                jTextFieldtDuracion.setText(Integer.toString(pelicula.getDuracion()));
                jTextFieldtGenero.setText(pelicula.getGenero());
                
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EditorPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(pelicula.toString());
    }
    
    private int accion, id;
    protected ConectorDB conector;
    protected Connection conexionOCI;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldtAnno;
    private javax.swing.JTextField jTextFieldtDirector;
    private javax.swing.JTextField jTextFieldtDuracion;
    private javax.swing.JTextField jTextFieldtGenero;
    private javax.swing.JTextField jTextFieldtITitulo;
    // End of variables declaration//GEN-END:variables
}
